parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: root
    mailer_transport: gmail
    mailer_host: 127.0.0.1
    mailer_user: bourdel.maxime.pro@gmail.com
    mailer_password: null
    locale: en
    secret: 039c5e4aa1d931065f999917d33042d7c7128176
    database_path: null
