parameters:
#    sdz_blog.example.class: Sdz\BlogBundle\Example

services:
    sdzblog.beta_listener: 
        class: Sdz\BlogBundle\Beta\BetaListener
        arguments: ["2014-08-02"]
        tags:
                    - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }